#!/bin/bash

# Lemonbar Start

# Duration
duration=5

# Geometry
barx() {
	x=`xrandr | grep '*' | cut -c 4-7`
	y=2
	z=$(( ($x / $y) - (${barw} / 2) ))
#	w=$(( $z - ${barw} ))
	echo $z
}

bary=10
barw=200
barh=40

# Colors
barbg=#05104D
barfg=#D41150

# Font
barfont="xft:Droid Sans:size=12"
icons="FontAwesome:size=12"

(echo "%{c}$@"; sleep ${duration}) | lemonbar -g ${barw}x${barh}+$(barx)+${bary} -B ${barbg} -f ${barfont} -f ${icons} -d
