#!/bin/bash

# Lemonbar Data

# Icon Support
icon() {
    echo -n -e "%{F$pIcon}\u$1 %{F$pFG}"
}

# Define Clock
clock() {
	icon f017
	date '+%I:%M:%S'
}

cal() {
	icon f073
	date '+%D'
}

while :; do
	buf=""
	buf="${buf} $(clock) "
	buf="${buf} $(cal) "

	echo $buf
	sleep 1
done
