#!/bin/bash

# Based on http://openweathermap.org/current

API_KEY="7a7d94b8c5f90a95df461c91fcf8c33d"

# Check on http://openweathermap.org/find
CITY_ID="4562407"

# Weather Status

URGENT_LOWER=10
URGENT_HIGHER=90

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""

SYMBOL_CELSIUS="℉"

WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=imperial"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_OUT= ~/.lemonbar/bar "Weather: ${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"


if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
  echo "${WEATHER_OUT}"
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
  echo "${WEATHER_OUT}"
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
  echo "${WEATHER_OUT}"
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
  echo "${WEATHER_OUT}"
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
  echo "${WEATHER_OUT}"
else
  echo "${WEATHER_OUT}"
fi

if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi
