#! /bin/bash

if (xrandr -q | grep "HDMI2 connected" && xrandr -q | grep -q "DP1 disconnected")
then
	exec xrandr --output eDP1 --off --output HDMI2 --mode 1920x1080
elif (xrandr -q | grep -q "HDMI2 connected" && xrandr -q | grep -q "DP1 connected")
then
	exec xrandr --output HDMI2 --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --mode 1920x1080 --pos 1920x0 --rotate normal --output eDP1 --off
else
	exec xrandr --output eDP1 --mode 1366x768 --output HDMI2 --off
fi
