#! /bin/bash

# HDMI 2 Config

if (xrandr -q | grep "HDMI2 connected"); then
	xrandr --output eDP1 --off --output HDMI2 --mode 1920x1080
else
	xrandr --output eDP1 --mode 1366x768 --output HDMI2 --off
fi
